server:
  port: 9102

spring:
  application:
    name: microservice-produits
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
