server:
  port: 9003

spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    sql-script-encoding: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/