server:
  port: 9001

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""

eureka:
  client:
    service-url:
      default-zone: http://localhost:9102/eureka/

# Nos configurations
mes-configs:
  limitDeProduits: 5
